services:
  node:
    container_name: quiz-node
    build:
      dockerfile: ../docker/node/Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      NODE_ENV: development

  php:
    container_name: quiz-php
    build:
      dockerfile: ../docker/php/Dockerfile
      context: ./backend
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./backend:/app
      - ./docker/php/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true

  postgres:
    container_name: quiz-postgres
    image: postgres:18
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
